
name: Master Java CI with Maven

on:
  push:
    branches: [ master ]      
    paths-ignore: 
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'docs/**'

jobs:

   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 11
         uses: actions/setup-java@v1
         with:
           java-version: 11
       - name: Build with Maven
         run: mvn -B package --file pom.xml

  #     - run: mkdir staging && cp target/*.jar staging
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: ${{ env.ARTIFACT }}
  #         path: staging
        
  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 11
  #     - name: Unit test
  #       run: mvn org.jacoco:jacoco-maven-plugin:0.8.5:prepare-agent test surefire-report:report-only
  
  #     - name: Download package
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ${{ env.ARTIFACT }}
  #         path: target/
  #     - name: Display structure of downloaded files
  #       run: ls -RS
  #       working-directory: target

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
              # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=056174
             -Dsonar.host.url=https://sonarqube.aa.com/
             -Dsonar.projectKey=runway-auth-poc
             -Dsonar.sources=.
             -X

 #  - name: SonarCloud Scan
  #    uses: sonarsource/sonarcloud-github-action@master
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  # download:
  #     - name: Deploy to Azure WebApp
  #       uses: azure/webapps-deploy@v2
  #       with: 
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.DEV_AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: target/*.jar

