
name: Master Java CI with Maven

on:
  push:
    branches: [ master ]      
    paths-ignore: 
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'docs/**'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  ARTIFACT: 'package'
  AZURE_WEBAPP_NAME: 'ghc-helloworldjava'
  GITHHUB_PACKAGE_TOKEN: ${{ secrets.GITHHUB_PACKAGE_TOKEN }}

jobs:

  #build:
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Set up JDK 11
    #     uses: actions/setup-java@v1
    #     with:
    #       java-version: 11
    #   - name: Build with Maven
    #     run: mvn -B package --file pom.xml

  #     - run: mkdir staging && cp target/*.jar staging
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: ${{ env.ARTIFACT }}
      #     path: staging
        
  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 11
  #     - name: Unit test
  #       run: mvn org.jacoco:jacoco-maven-plugin:0.8.5:prepare-agent test surefire-report:report-only
  
  # publish:
  #   runs-on: ubuntu-latest
  #   #needs: [unit-test]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 11
      # - name: Publish to GitHub Packages
      #   run: mvn deploy -ssettings.xml -DGHP_PUBLISH_TOKEN=${{ secrets.GHP_PUBLISH_TOKEN }} 


  # failure-cleanup:
  #   runs-on: ubuntu-latest
  #   if: ${{ failure() }}
  #   steps:
  #     - uses: actions/delete-package-versions@v1
  #       with:
  #         package-version-ids: '${{ version }}'
  #         token: ${{ secrets.GITHUB_PAT }}

  deploy-dev:
    #needs: [build, unit-test]
    env:
      AZURE_WEBAPP_NAME: 'dev-ghc-helloworldjava'  # set this to your application's name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check settings
        run:  |
             ls -l
             pwd
      - name: Download package
        run: mvn install -X -ssettings.xml -DGHP_DOWNLOAD_TOKEN=${{ secrets.GHP_DOWNLOAD_TOKEN }}
      - name: Check downloads
        run:  |
             ls -l /home/runner/.m2/repository/com/aa/hello
             ls -l
             ls -l target 
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.DEV_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: /home/runner/.m2/repository/com/aa/hello/0.0.3/*.jar

  #     - name: Download package
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ${{ env.ARTIFACT }}
  #         path: target/
  #     - name: Display structure of downloaded files
  #       run: ls -RS
  #       working-directory: target
        
      # - name: Deploy to Azure WebApp
      #   uses: azure/webapps-deploy@v2
      #   with: 
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.DEV_AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: target/*.jar

  # delete-artifact:
  #   needs: [build, unit-test,deploy-dev]
  #   runs-on: ubuntu-latest
  # #   if: ${{ failure() }}
  #   steps:
  #     - name: Delete package
  #       uses: actions/delete-package-versions@v1
  #       with:
  #         name: ${{ env.ARTIFACT }}
